### ISSUE TITLE
Better backup method

### ISSUE THREAD

**Issue by JustAnotherArchivist** [ovsoinc/gitbackup#10]
The code currently essentially uses this method for retrieving the repositories:

* When a repo is encountered for the first time, a plain `git clone`
* At later times, `git fetch origin master`
* To get it into one file, `zip -r`

This has a number of downsides:

* All branches other than master are never updated.
* Some refs are never fetched at all, e.g. PRs I believe.
* There will be some duplication within the ZIP since it contains both the `.git` directory and a full working copy.

A better solution would be to `git clone --mirror`; this is supposed to be a truly complete copy of the remote repository. The command for updating such a clone is apparently [`git remote update`](https://stackoverflow.com/questions/6150188/how-to-update-a-git-clone-mirror). And the proper file format for storing the dumped repository would be a bundle, which can be created using `git bundle create FILENAME --all` inside the mirror.

(See also: https://www.archiveteam.org/index.php?title=GitHub#git_itself)

I do *not* know whether this is the optimal solution. It's definitely possible that there are better ways still. It should be tested thoroughly (e.g. does it fetch new PRs/branches/tags, do force-pushes on PRs get treated properly such that all commits get fetched). The import functions on GitLab, Gitea, etc. might be worth looking into, or asking on the git mailing list.

**Comment by montyanderson** [comment]
@JustAnotherArchivist This seems to be a better solution.

However, this leads to a problem: how does the script know if the repository has changed in order to re-bundle or re-zip it?

**Comment by JustAnotherArchivist** [comment]
@montyanderson If I'm reading the current code correctly, you're already keeping a copy of the repository itself in a separate directory; if the directory exists, you fetch (and check whether it needs to be zipped again by looking at the commit count since the previous retrieval), otherwise you clone. So in that sense, nothing would change. The check for whether there's been a change would have to be more complicated than the current `git rev-list HEAD...origin/master --count` since you'd have to account for master still being the same but other things having changed, new branches or tags, and a variety of other things. I don't know what the proper way for that is.

Another thing to consider is what should happen when a branch (or tag) was deleted on the remote. That depends on your goals: if this is supposed to be a backup, then it should also be dropped from the bundle; if this is supposed to be an archive, then I think you'd have to keep all bundles, similar to how the Wayback Machine keeps all web page snapshots. While the creation of incremental bundles is [possible (although not simple)](https://stackoverflow.com/a/12216898), I don't think that would capture a branch deletion, so you'd likely have to create a full bundle every time to properly capture this. Maybe there is a clever way to deduplicate the bundles against each other, but it might be tricky since I believe that bundles are basically a list of refs and a zlib-compressed packfile; the compression will of course interfere with deduplication.
